apiVersion: v2
name: scalyr-agent
description: A Helm chart for deploying the Scalyr agent
type: application
version: 0.2.2
appVersion: 2.1.20
keywords:
  - scalyr
  - logging
  - monitoring
  - metrics
home: https://github.com/dodevops/helm-scalyr
icon: https://app.scalyr.com/s2/src/img/logo-reverse.png
sources:
  - https://github.com/dodevops/helm-scalyr
maintainers:
  - name: dploeger
    email: develop@dieploegers.de
    url: https://github.com/dploeger
