name: "Lint and Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  lint_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1.1
        with:
          version: v3.7.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@5f16c27cf7a4fa9c776ff73734df3909b2b65127 # v2.1.0
        with:
          version: v3.4.0

      - name: Run chart-testing (lint)
        run: |
          ct lint --debug --charts . --chart-dirs "$(pwd)"

      - name: Create kind cluster
        uses: helm/kind-action@94729529f85113b88f4f819c17ce61382e6d8478 # v1.2.0

      # TODO: Configure testing write API key as Github repo secret
      # TODO: Ideally we would also use read api key to confirm agent.log is correctly ingested
      # TODO: Run install twice (against US and EU)
      - name: Run chart-testing (install) - daemonset controller type
        env:
          API_KEY: "tbd" # reference secret
        run: |
          # Write test values to a file which is used by ct install
          mkdir -p ci/
          echo -e 'controllerType: "daemonset"\nscalyr:\n  apiKey: "${API_KEY}"' > ci/test-values.yaml

          ct install --debug --charts . --chart-dirs "$(pwd)"

      - name: Run chart-testing (install) - deployment controller type
        env:
          API_KEY: "tbd" # reference secret
        run: |
          # Write test values to a file which is used by ct install
          mkdir -p ci/
          echo -e 'controllerType: "deployment"\nscalyr:\n  apiKey: "${API_KEY}"' > ci/test-values.yaml

          ct install --debug --charts . --chart-dirs "$(pwd)"
